# Workflow that installs SNOwGLoBES and runs an integration test

name: Integration Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  run:
    # Only execute integration test if PR is *not* a draft
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest
    strategy:
      # Add a list of python versions we want to use for testing.
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install SNEWPY
        run: |
          pip install ".[dev]"
      - name: Run Integration Tests
        run: |
          python -m unittest python/snewpy/test/simplerate_integrationtest.py
          pytest -m 'snowglobes'
