# This workflows will upload a Python Package using Twine when a release is published
# Based on https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish to PyPI

on:
  push:
    # branches: [ 'JostMigenda/lazyDownloads' ] # only for testing
    tags: # Sequence of patterns matched against refs/tags
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
#   release:
#     types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build # and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_JM }}
      run: |
        python -c 'import python.snewpy; python.snewpy._get_model_urls()'
        cat python/snewpy/_model_urls.py
        python -c 'import python.snewpy; python.snewpy.get_models(models="Bollig_2016")'
        rm -r SNEWPY_models/
        python setup.py sdist bdist_wheel
        twine upload --repository testpypi dist/*
